title: Disney Dreaming
author: Whimsicurl Creations
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a girl doing a bit of Disney dreaming...
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
