title: Dreaming of Disney
author: Whimsicurl Creations
email: blmeier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A dream is a wish your heart makes...

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
